[workspace]
resolver = "2"
members = ["crates/openbaud-core", "crates/openbaud"]

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
schemars = "1"
thiserror = "2"
anyhow = "1"
